"""Add favorite column to Template

Revision ID: 89797f3fd11a
Revises: 
Create Date: 2025-03-25 10:23:55.154493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89797f3fd11a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_column('favorite')

    # ### end Alembic commands ###
