"""add transcription_expires_at

Revision ID: a746f4c00b19
Revises: 89797f3fd11a
Create Date: 2025-05-14 05:17:57.348794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a746f4c00b19'
down_revision = '89797f3fd11a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transcription_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('transcription_expires_at')

    # ### end Alembic commands ###
